- name: Create a Directory to export items to
  file:
    path: "{{ _jbosseapappmigration_exported_resources_dir }}/{{ _jbosseapappmigration_name }}-app"
    state: directory
    mode: '0777'

- name: check ImageStreams to Export
  shell: oc get is -n {{ _jbosseapappmigration_namespace }} --no-headers | awk '{print $1}'
  register: current_iss

- name: Export ImageStreams
  shell: oc get is "{{ item }}" -n {{ _jbosseapappmigration_namespace }} --export -o yaml > "{{ _jbosseapappmigration_exported_resources_dir }}/{{ _jbosseapappmigration_name }}-app/existing-is-{{ item }}".yml
  with_items: 
    - "{{ current_iss.stdout_lines }}" 
  when: current_iss.stdout_lines | length > 0 

- name: check BuildConfigs to Export
  shell: oc get bc -n {{ _jbosseapappmigration_namespace }} --no-headers | awk '{print $1}'
  register: current_bcs

- name: Export BuildConfigs
  shell: oc get bc "{{ item }}" -n {{ _jbosseapappmigration_namespace }} --export -o yaml > "{{ _jbosseapappmigration_exported_resources_dir }}/{{ _jbosseapappmigration_name }}-app/existing-bc-{{ item }}".yml
  with_items: 
    - "{{ current_bcs.stdout_lines }}" 
  when: current_bcs.stdout_lines | length > 0 

- name: check Deployment Configs to Export
  shell: oc get dc -n {{ _jbosseapappmigration_namespace }} --no-headers | egrep -i "{{ _jbosseapappmigration_name }}" | awk '{print $1}'
  register: current_dcs

- name: Export Deployment Configs
  shell: oc get dc "{{ item }}" -n {{ _jbosseapappmigration_namespace }} --export -o yaml > "{{ _jbosseapappmigration_exported_resources_dir }}/{{ _jbosseapappmigration_name }}-app/existing-dc-{{ item }}".yml
  with_items: 
    - "{{ current_dcs.stdout_lines }}" 
  when: current_dcs.stdout_lines | length > 0 

- name: check Running Pods to Export binary out of
  shell: oc get po -n {{ _jbosseapappmigration_namespace }} --no-headers | egrep -i "{{ _jbosseapappmigration_name }}" | egrep -i running | awk '{print $1}'
  register: current_pos

- name: Get List of artifacts running inside the Pod above
  shell: oc rsh -n {{ _jbosseapappmigration_namespace }} "{{ current_pos.stdout_lines[0] }}" ls /deployments
  when: 
    - current_pos.stdout_lines is defined 
    - current_pos.stdout_lines | length > 0
  register: current_artifacts

- name: Print output of running artifacts
  debug:
    var: current_artifacts 

- name: Export Configuration and artifacts directories from pod
  shell: oc rsync -n {{ _jbosseapappmigration_namespace }} {{ current_pos.stdout_lines[0] }}:{{ item }} {{ _jbosseapappmigration_exported_resources_dir }}/{{ _jbosseapappmigration_name }}-app 
  when: 
    - current_pos.stdout_lines | length > 0
    - current_artifacts.stdout_lines | length > 0
  with_items:
    - /deployments
    - /opt/eap/standalone/configuration
