- name: Create temp k8s object storage directory
  file:
    state: directory
    path: "{{ _jbosseapappmigration_exported_resources_dir }}/{{ _jbosseapappmigration_name }}"
  register: tmpdir

- name: Lookup All Secrets
  set_fact:
    current_secrets: "{{ lookup('k8s', api_version='v1', kind='Secret', namespace=_jbosseapappmigration_namespace) }}"

- name: Prints List of looked up secrets
  debug:
    var: current_secrets

- name: Print Filtered current secrets
  debug:
    var: item | to_yaml
  with_items:
    - "{{ current_secrets }}"
  when:
    - current_secrets | length > 0
    - "('default' not in item.metadata.name)"
    - "('deployer' not in item.metadata.name)"
    - "('builder' not in item.metadata.name)"
    - "('-token-' not in item.metadata.name)"
    - "('-dockercfg-' not in item.metadata.name)"

- name: Save Secrets into temp dir
  copy:
    #content: "{{ (item | combine({'apiVersion': 'v1', 'kind': 'Secret'})) | to_yaml }}"
    content: "{{ ({'apiVersion': 'v1', 'kind': 'Secret'} | combine(item)) | to_yaml }}"
    #content: "{{ (( {'apiVersion': 'v1'} | combine({'kind': 'Secret'})) | combine(item) ) | to_yaml }}"
    #content: "{{ ((item | combine({'apiVersion': 'v1'})) | combine({'kind': 'Secret'})) | to_yaml }}"
    dest: "{{ tmpdir.path }}/{{ item.metadata.name }}-secret.yml"
  with_items:
    #- "{{ current_secrets | list }}"
    - "{{ current_secrets }}"
  when:
    - current_secrets | length > 0
    - "('default' not in item.metadata.name)"
    - "('deployer' not in item.metadata.name)"
    - "('builder' not in item.metadata.name)"
    - "('-token-' not in item.metadata.name)"
    - "('-dockercfg-' not in item.metadata.name)"
  register: saved_secrets

- name: Print output of saved secrets
  debug:
    var: saved_secrets.results

- name: Print Each saved secret for sanity check
  shell: cat {{ item.dest }}
  with_items:
    - "{{ saved_secrets.results }}"
  when:
    - saved_secrets | length > 0
    - item.dest is defined

- name: Lookup All ServiceAccounts
  set_fact:
    current_sas: "{{ lookup('k8s', api_version='v1', kind='ServiceAccount', namespace=_jbosseapappmigration_namespace) }}"

- name: Save ServiceAccounts into temp dir
  copy:
    content: "{{ {'apiVersion': 'v1', 'kind': 'ServiceAccount'} | combine(item) | to_yaml }}"
    #content: "{{ (( {'apiVersion': 'v1'} | combine({'kind': 'ServiceAccount'})) | combine(item) ) | to_yaml }}"
    #content: "{{ (( item | combine({'apiVersion': 'v1'})) | combine({'kind': 'ServiceAccount'})) | to_yaml }}"
    dest: "{{ tmpdir.path }}/{{ item.metadata.name }}-sa.yml"
  with_items:
    #- "{{ current_sas | list }}"
    - "{{ current_sas }}"
  when:
    - "('default' not in item.metadata.name)"
    - "('deployer' not in item.metadata.name)"
    - "('builder' not in item.metadata.name)"
  register: saved_sas

- name: Lookup All ConfigMaps
  set_fact:
    current_cms: "{{ lookup('k8s', api_version='v1', kind='ConfigMap', namespace=_jbosseapappmigration_namespace) }}"

- name: Save ConfigMaps into temp dir
  copy:
    content: "{{ {'apiVersion': 'v1', 'kind': 'ConfigMap'} | combine(item) | to_yaml }}"
    #content: "{{ (( {'apiVersion': 'v1'} | combine({'kind': 'ConfigMap'})) | combine(item) ) | to_yaml }}"
    #content: "{{ (( item | combine({'apiVersion': 'v1'})) | combine({'kind': 'ConfigMap'})) | to_yaml }}"
    dest: "{{ tmpdir.path }}/{{ item.metadata.name }}-cm.yml"
  with_items:
    - "{{ current_cms | list }}"
    #- "{{ current_cms }}"
  register: saved_cms

- name: Lookup All RoleBindings
  set_fact:
    #current_rbs: "{{ lookup('k8s', kind='RoleBinding', namespace=_jbosseapappmigration_namespace) }}"
    current_rbs: "{{ lookup('k8s', api_version='rbac.authorization.k8s.io/v1', kind='RoleBinding', namespace=_jbosseapappmigration_namespace) }}"

- name: Save RoleBindings into temp dir
  copy:
    content: "{{ {'apiVersion': 'rbac.authorization.k8s.io/v1', 'kind': 'RoleBinding'} | combine(item) | to_yaml }}"
    #content: "{{ (( {'apiVersion': 'rbac.authorization.k8s.io/v1'} | combine({'kind': 'RoleBinding'})) | combine(item) ) | to_yaml }}"
    #content: "{{ (( item | combine({'apiVersion': 'rbac.authorization.k8s.io/v1'})) | combine({'kind': 'RoleBinding'})) | to_yaml }}"
    dest: "{{ tmpdir.path }}/{{ item.metadata.name }}-rb.yml"
  with_items:
    - "{{ current_rbs | list }}"
    #- "{{ current_rbs }}"
  when:
    - "('admin' not in item.metadata.name)"
    - "('deployer' not in item.metadata.name)"
    - "('builder' not in item.metadata.name)"
  register: saved_rbs

- name: Lookup All Services
  set_fact:
    current_svcs: "{{ lookup('k8s', api_version='v1', kind='Service', namespace=_jbosseapappmigration_namespace) }}"

- name: Save Services into temp dir
  copy:
    content: "{{ {'apiVersion': 'v1', 'kind': 'Service'} | combine(item) | to_yaml }}"
    #content: "{{ (( {'apiVersion': 'v1'} | combine({'kind': 'Service'})) | combine(item) ) | to_yaml }}"
    #content: "{{ (( item | combine({'apiVersion': 'v1'})) | combine({'kind': 'Service'})) | to_yaml }}"
    dest: "{{ tmpdir.path }}/{{ item.metadata.name }}-svc.yml"
  with_items:
    #- "{{ current_svcs | list }}"
    - "{{ current_svcs }}"
  when:
    - item.metadata.name and item.metadata.name is defined
  register: saved_svcs

- name: Lookup All Routes
  set_fact:
    current_routes: "{{ lookup('k8s', api_version='v1', kind='Route', namespace=_jbosseapappmigration_namespace) }}"

- name: Save Routes into temp dir
  copy:
    content: "{{ {'apiVersion': 'v1', 'kind': 'Route'} | combine(item) | to_yaml }}"
    #content: "{{ (( {'apiVersion': 'v1'} | combine({'kind': 'Route'})) | combine(item) ) | to_yaml }}"
    #content: "{{ (( item | combine({'apiVersion': 'v1'})) | combine({'kind': 'Route'})) | to_yaml }}"
    dest: "{{ tmpdir.path }}/{{ item.metadata.name }}-route.yml"
  with_items:
    #- "{{ current_routes | list }}"
    - "{{ current_routes }}"
  register: saved_routes

