---
# tasks file for jbosseapappmigration
- name: Include existing resource export tasks
  #import_tasks: export-existing.yml
  import_tasks: export-existing-k8s.yml

- name: Include running app binary and deployment config export tasks
  #import_tasks: export-existing-app-deployment.yml
  import_tasks: export-existing-app-deployment-k8s.yml

- name: Include exported deployment config cleaning tasks
  #import_tasks: clean-exported-resources.yml
  import_tasks: clean-exported-resources.yml

- name: Include migrate app rebuild and support config tasks
  #import_tasks: deploy-migrated-app-liftandshift-style.yml
  import_tasks: deploy-migrated-app-liftandshift-style-k8s.yml
