apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  annotations:
    capabilities: Seamless upgrade of Jboss EAP container and lift and shift migration of deployed application
    categories: Application Runtime
    certified: 'false'
    containerImage: 'quay.io/cadjai/jboss-eap-app-migration-operator:v0.0.1'
    createdAt: '2019-09-17T17:15:00Z'
    description: 'Migrate JBoss EAP container from existing EAP version to a new major version on OpenShift.'
    repository: 'https://gitlab.com:claudianus/kitchensink-migration-operator'
    support: 'community'
    alm-examples: '[{"apiVersion":"rhtconsulting.eapquickstarts.dev/v1alpha1","kind":"JbossEapAppMigration","metadata":{"name":"kitchensink-jbosseapappmigration"},"spec":{"_jbosseapappmigration_name":"kitchensink","_jbosseapappmigration_namespace":"eap6-kitchensink","_jbosseapappmigration_namespace_new":"eap7-kitchensink","_jbosseapappmigration_runtime_image":"registry.redhat.io/jboss-eap-6/eap64-openshift","_jbosseapappmigration_runtime_image_new":"registry.redhat.io/jboss-eap-7/eap72-openshift","_jbosseapappmigration_runtime_image_tag":"latest","_jbosseapappmigration_runtime_image_tag_new":"latest","_jbosseapappmigration_state":"present"}},{"apiVersion":"rhtconsulting.eapquickstarts.dev/v1alpha1","kind":"JbossEapAppMigration","metadata":{"name":"example-jbosseapappmigration"},"spec":{"_jbosseapappmigration_name":"kitchensink","_jbosseapappmigration_namespace":"eap6-kitchensink","_jbosseapappmigration_namespace_new":"eap7-kitchensink","_jbosseapappmigration_runtime_image":"registry.redhat.io/jboss-eap-6/eap64-openshift","_jbosseapappmigration_runtime_image_new":"registry.redhat.io/jboss-eap-7/eap72-openshift","_jbosseapappmigration_runtime_image_tag":"latest","_jbosseapappmigration_runtime_image_tag_new":"latest","_jbosseapappmigration_state":"present"}}]'
    capabilities: Basic Install
  name: jboss-eap-app-migration-operator.v0.0.1
  namespace: jboss-eap-app-migration-operator 
spec:
  apiservicedefinitions: {}
  customresourcedefinitions: 
    owned:
      - kind: JbossEapAppMigration
        name: jbosseapappmigration.rhtconsulting.eapquickstarts.dev
        version: v1alpha1
        description: 'An example JBoss EAP App Migration.'
        displayName: JBoss EAP APP Migration
        resources:
          - kind: ServiceAccount
            version: v1
          - kind: Role
            version: v1
          - kind: RoleBinding
            version: v1
          - kind: Deployment
            version: v1
          - kind: ReplicaSet
            version: v1
          - kind: Pods
            version: v1 
        specDescriptors: [] 
        statusDescriptors: []
  description: |
    JBoss EAP app migration when a major version of the container is available. 
  displayName: 'Jboss Eap App Migration Operator'
  icon: 
  - base64data: "iVBORw0KGgoAAAANSUhEUgAAAAEAAAKeCAIAAADr2OZhAAAAGXRFWHRTb2Z0d2FyZQBBZG9iZSBJbWFnZVJlYWR5ccllPAAAAeNJREFUeNrEVllyxTAIQ73/UXqNzvRWqhdsBLH7OvM++uFJ4gULASL4/vr8MLO3Btpgf0cbPMyv4etjHjLP2Is2T64nph1Q7La58Y1kczyNc92y7b52w6g4n3vmXXA7bN/od1QbZX9g6GfnO2+cjfPZH7htOu5x95iH+yjYqFy2OXZ8zptlLIEfjlfeB9/NHhA8bl4d7/7OODBsW/reeJJ/jPMlLpuPFfvF0/APk4exTucl/Mr5iMIxE+bOISUPd/x+zXHhxDwfGiam3GHkCMKnv9kN3BB/CLmv84fp/4y9c2OR+52TxKXVPFi5i6gXVv/xqJuavw+/lk0r2FbcvYYGNyuXFdMxbpbroXJ6w/0Yzsul7qNmyznl6KQ7Jz62Fp33rTwMTnN9jrWkBSy590J/xSeK9pjm6I5V8LN1GfPc0jLYgfcHHucH2PU5NcXvlxipHV5yaen/kTvpAbPGuLVy33/g1Mq9ma/pD0V3N2ZKzKF6J+cveDUnaJHDp9yteOicPjj3+IAlH1UXTpwBSSdR9Iyia7tHlD3JtnLC2vOyppvUbo03U69YZ6quI/epotdZAxcPkhOlh9kLTHb5R7jHyqT/qfZFzxzru4dNzvj4r1l9jkUn7e3/s9P/kNm/jh8BBgCRJgPK9epwSAAAAABJRU5ErkJggg=="
    mediatype: image/png
  install:
    spec:
      deployments:
      - name: jboss-eap-app-migration-operator
        spec:
          replicas: 1
          selector:
            matchLabels:
              name: jboss-eap-app-migration-operator
          strategy: {}
          template:
            metadata:
              labels:
                name: jboss-eap-app-migration-operator
            spec:
              containers:
              - command:
                - /usr/local/bin/ao-logs
                - /tmp/ansible-operator/runner
                - stdout
                image: quay.io/cadjai/jboss-eap-app-migration-operator:v0.0.1
                imagePullPolicy: Always
                name: ansible
                resources: {}
                volumeMounts:
                - mountPath: /tmp/ansible-operator/runner
                  name: runner
                  readOnly: true
              - env:
                - name: WATCH_NAMESPACE
                  valueFrom:
                    fieldRef:
                      fieldPath: metadata.annotations['olm.targetNamespaces']
                - name: POD_NAME
                  valueFrom:
                    fieldRef:
                      fieldPath: metadata.name
                - name: OPERATOR_NAME
                  value: jboss-eap-app-migration-operator
                image: quay.io/cadjai/jboss-eap-app-migration-operator:v0.0.1
                imagePullPolicy: Always
                name: operator
                resources: {}
                volumeMounts:
                - mountPath: /tmp/ansible-operator/runner
                  name: runner
              serviceAccountName: jboss-eap-app-migration-operator
              volumes:
              - emptyDir: {}
                name: runner
      permissions:
      - rules:
        - apiGroups:
          - ""
          resources:
          - pods
          - services
          - endpoints
          - persistentvolumeclaims
          - events
          - configmaps
          - secrets
          verbs:
          - '*'
        - apiGroups:
          - apps
          resources:
          - deployments
          - daemonsets
          - replicasets
          - statefulsets
          verbs:
          - '*'
        - apiGroups:
          - route.openshift.io
          resources:
          - routes
          verbs:
          - create
          - update
          - delete
          - get
          - list
          - watch
          - patch
        - apiGroups:
          - image.openshift.io
          resources:
          - image
          - imagestream
          - imagestreamtag
          verbs:
          - create
          - update
          - delete
          - get
          - list
          - watch
          - patch
        - apiGroups:
          - build.openshift.io
          resources:
          - build
          - buildconfig
          verbs:
          - create
          - update
          - delete
          - get
          - list
          - watch
          - patch
        - apiGroups:
          - apps.openshift.io
          resources:
          - deploymentconfig
          verbs:
          - create
          - update
          - delete
          - get
          - list
          - watch
          - patch
        - apiGroups:
          - project.openshift.io
          resources:
          - project
          - projectrequest
          verbs:
          - create
          - update
          - delete
          - get
          - list
          - watch
          - patch
        - apiGroups:
          - authorization.openshift.io
          resources:
          - role
          - rolebinding
          verbs:
          - create
          - update
          - delete
          - get
          - list
          - watch
          - patch
        - apiGroups:
          - apps
          resourceNames:
          - jboss-eap-app-migration-operator
          resources:
          - deployments/finalizers
          verbs:
          - update
        - apiGroups:
          - rhtconsulting.eapquickstarts.dev
          resources:
          - jbosseapappmigrations
          - jbosseapappmigrations/status
          verbs:
          - create
          - update
          - delete
          - get
          - list
          - watch
          - patch
        serviceAccountName: jboss-eap-app-migration-operator
    strategy: deployment
  installModes:
  - supported: true
    type: OwnNamespace
  - supported: true
    type: SingleNamespace
  - supported: false
    type: MultiNamespace
  - supported: true
    type: AllNamespaces
  maturity: alpha
  maintainers: 
  - name: Red Hat
    email: openshift-operators@redhat.com
  provider: 
    name: Red Hat
  links:
  - name: Operator Source Code
    url: https://gitlab.com/claudianus/kitchensink-migration-operator.git 
  version: 0.0.1
