- hosts: localhost
  gather_facts: no
  vars:
  - _jbosseapappmigration_state: present
  - _jbosseapappmigration_namespace: eap7-app
  - _jbosseapappmigration_namespace_new: eap7-app-new
  - _jbosseapappmigration_name: eap7-kitchensink 
  - _jbosseapappmigration_runtime_image: registry.redhat.io/jboss-eap-7/eap72-openshift
  - _jbosseapappmigration_runtime_image_tag: latest 
  - _jbosseapappmigration_runtime_image_new: registry.redhat.io/jboss-eap-7/eap70-openshift
  - _jbosseapappmigration_runtime_image_tag_new: latest 

  tasks:
  - name: Include existing resource export tasks
    import_tasks: roles/jbosseapappmigration/tasks/export-existing.yml

  - name: Include running app binary and deployment config export tasks
    import_tasks: roles/jbosseapappmigration/tasks/export-existing-app-deployment.yml

  - name: Include exported deployment config cleaning tasks
    import_tasks: roles/jbosseapappmigration/tasks/clean-exported-resources.yml

  - name: Include migrate app rebuild and support config tasks
    import_tasks: roles/jbosseapappmigration/tasks/deploy-migrated-app-liftandshift-style.yml
