apiVersion: apps/v1
kind: Deployment
metadata:
  name: jboss-eap-app-migration-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: jboss-eap-app-migration-operator
  template:
    metadata:
      labels:
        name: jboss-eap-app-migration-operator
    spec:
      serviceAccountName: jboss-eap-app-migration-operator
      containers:
        - name: ansible
          command:
          - /usr/local/bin/ao-logs
          - /tmp/ansible-operator/runner
          - stdout
          # Replace this with the built image name
          image: "docker pull quay.io/cadjai/jboss-eap-app-migration-operator:v0.0.1"
          imagePullPolicy: "IfNotPresent"
          volumeMounts:
          - mountPath: /tmp/ansible-operator/runner
            name: runner
            readOnly: true
        - name: operator
          # Replace this with the built image name
          image: "docker pull quay.io/cadjai/jboss-eap-app-migration-operator:v0.0.1"
          imagePullPolicy: "IfNotPresent"
          volumeMounts:
          - mountPath: /tmp/ansible-operator/runner
            name: runner
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "jboss-eap-app-migration-operator"
      volumes:
        - name: runner
          emptyDir: {}
